Files already downloaded and verified
Files already downloaded and verified
[D_DSFL][cifar10][resnet18][123]20230917-202437
Traceback (most recent call last):
  File "/home/gyoon814/DepthSFL/research/DSFL_new_gkt/main_new.py", line 49, in <module>
    main_DDepthSFL(args)
  File "/home/gyoon814/DepthSFL/research/DSFL_new_gkt/main_DDepthSFL_new.py", line 97, in main_DDepthSFL
    weight_c, weight_a_c, kd_logits_client,  args, loss_c, acc_c = local_c.train(
  File "/home/gyoon814/DepthSFL/research/DSFL_new_gkt/train/train_DDepthSFL_new.py", line 115, in train
    fx_client = net_client(images)
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gyoon814/DepthSFL/research/DSFL_new_gkt/model/model_DDepthSFL/resnet18_flop.py", line 49, in forward
    out1 = self.maxpool(F.relu(self.bn1(self.conv1(x))))
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor